export const CustomErrorCode = {
  COMMON__INVALID_DATA_FIELD: 40000,
  COMMON__INVALID_SELF_INVOKE: 40001,
  SEND_FRIEND_REQUEST__NO_TARGET: 40002,

  LOGIN__ACCOUNT_NOT_VERIFIED: 40300,
  SEND_DM__BLOCKED: 40301,

  COMMON__ACCOUNT_NOT_FOUND: 40400,
  COMMON__TARGET_NOT_FOUND: 40401,
  REFRESH__SESSION_NOT_FOUND: 40402,
  LOGOUT__SESSION_NOT_FOUND: 40403,

  REGISTER__EMAIL_EXISTS: 40900,
  REGISTER__USERNAME_EXISTS: 40901,
  VERIFY__INVALID_STATUS: 40902,
  SEND_FRIEND_REQUEST__ALREADY_FRIEND: 40903,
  SEND_FRIEND_REQUEST__BLOCKED: 40904,
  FRIEND_REQUEST_FEEDBACK__NO_REQUEST: 40905,
  REMOVE_FRIEND__NOT_FRIEND: 40906,
  UNBLOCK__NOT_BLOCKED: 40907,
  PIN_DM__ALREADY_PINNED: 40908,
};

export const CustomErrorMessage = {
  COMMON__ACCOUNT_NOT_FOUND: 'Account not found',
  COMMON__TARGET_NOT_FOUND: 'Target not found',
  COMMON__INVALID_DATA: 'Invalid data',
  COMMON__INVALID_SELF_INVOKE: 'Invalid self invoke',

  LOGIN__ACCOUNT_NOT_VERIFIED: 'Account not verified',

  REGISTER__AGE_RESTRICTION_VIOLATED: 'Age restriction violated',
  REGISTER__EMAIL_EXISTS: 'Email already exists',
  REGISTER__USERNAME_EXISTS: 'Username already exists',

  VERIFY__INVALID_STATUS: 'Invalid account status',

  REFRESH__SESSION_NOT_FOUND: 'Session not found',

  LOGOUT__SESSION_NOT_FOUND: 'Session not found',

  SEND_FRIEND_REQUEST__ALREADY_FRIEND: 'Already friend',
  SEND_FRIEND_REQUEST__BLOCKED: 'Blocked',

  FRIEND_REQUEST_FEEDBACK__NO_REQUEST: 'No request found',

  REMOVE_FRIEND__NOT_FRIEND: 'Not friend with this user',

  UNBLOCK__NOT_BLOCKED: 'This user is not blocked',

  PIN_DM__ALREADY_PINNED: 'This user is already pinned',

  SEND_DM__BLOCKED: 'This user blocked you'
};
